name: Deploy to Production

on:
  workflow_dispatch: {}

jobs:
  migrate-production-db:
    name: Migrate Production Database
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Migrate production database
        uses: ./.github/actions/migrate-db
        with:
          database-url: ${{ secrets.PROD_DATABASE_URL }}

  deploy-production:
    name: Deploy to Vercel Production
    runs-on: ubuntu-latest
    needs: migrate-production-db
    environment:
      name: Production
      url: https://www.kanakacreekpac.ca
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        id: deploy
        uses: ./.github/actions/vercel-deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          environment: production
          prod: "true"
